//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinnishPublicHolidays.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Holidays {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Holidays() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinnishPublicHolidays.Resources.Holidays", typeof(Holidays).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Saints&apos; Day.
        /// </summary>
        public static string AllSaintsDay {
            get {
                return ResourceManager.GetString("AllSaintsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascension Day.
        /// </summary>
        public static string AscensionDay {
            get {
                return ResourceManager.GetString("AscensionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxing Day.
        /// </summary>
        public static string BoxingDay {
            get {
                return ResourceManager.GetString("BoxingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Day.
        /// </summary>
        public static string ChristmasDay {
            get {
                return ResourceManager.GetString("ChristmasDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas Eve.
        /// </summary>
        public static string ChristmasEve {
            get {
                return ResourceManager.GetString("ChristmasEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter.
        /// </summary>
        public static string Easter {
            get {
                return ResourceManager.GetString("Easter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easter Sunday.
        /// </summary>
        public static string EasterSunday {
            get {
                return ResourceManager.GetString("EasterSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epiphany.
        /// </summary>
        public static string Epiphany {
            get {
                return ResourceManager.GetString("Epiphany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First of May.
        /// </summary>
        public static string FirstOfMay {
            get {
                return ResourceManager.GetString("FirstOfMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Friday.
        /// </summary>
        public static string GoodFriday {
            get {
                return ResourceManager.GetString("GoodFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finland&apos;s Independence Day.
        /// </summary>
        public static string IndepencenceDay {
            get {
                return ResourceManager.GetString("IndepencenceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midsummer&apos;s Day.
        /// </summary>
        public static string MidsummerDay {
            get {
                return ResourceManager.GetString("MidsummerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midsummer&apos;s Eve.
        /// </summary>
        public static string MidsummerEve {
            get {
                return ResourceManager.GetString("MidsummerEve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Years Day.
        /// </summary>
        public static string NewYearsDay {
            get {
                return ResourceManager.GetString("NewYearsDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentecost.
        /// </summary>
        public static string Pentecost {
            get {
                return ResourceManager.GetString("Pentecost", resourceCulture);
            }
        }
    }
}
